export default function RecommendDatas() {
  return [
    {
      id: "rcds001",
      name: "블랙티 앰플 기획 세트 [대용량] 50mL",
      hashTag: ["주름개선미백기능성", "블랙티"],
      frontImg: "rdIF_1.jpg",
      backImg: "rdIF_1.jpg",
    },
    {
      id: "rcds002",
      name: "블랙티 앰플 [대용량] 50mL + 블랙티 크림 45mL",
      hashTag: ["블랙티", "블랙티앰플"],
      frontImg: "rdIF_2.jpg",
      backImg: "rdIF_2.jpg",
    },
    {
      id: "rcds003",
      name: "링클 사이언스 스팟 트리트먼트 40mL",
      hashTag: ["주름개선효과", "미역추출물"],
      frontImg: "rdIF_3.jpg",
      backImg: "rdIB_3.jpg",
    },
    {
      id: "rcds004",
      name: "비자 트러블 로션 100mL",
      hashTag: ["트러블케어", "8무첨가"],
      frontImg: "rdIF_4.jpg",
      backImg: "rdIB_4.jpg",
    },
    {
      id: "rcds005",
      name: "블랙티 유스 인핸싱 크림 45mL",
      hashTag: ["주름개선미백기능성", "블랙티"],
      frontImg: "rdIF_5.jpg",
      backImg: "rdIB_5.jpg",
    },
    {
      id: "rcds006",
      name: "더마 그린티 프로바이오틱스 크림 50mL",
      hashTag: ["바르는유산균", "녹차세라마이드"],
      frontImg: "rdIF_6.jpg",
      backImg: "rdIB_6.jpg",
    },
    {
      id: "rcds007",
      name: "히알루론 수분 선크림 SPF50+PA++++ 50mL",
      hashTag: ["수분자차", "히알루론"],
      frontImg: "rdIF_7.jpg",
      backImg: "rdIB_7.jpg",
    },
    {
      id: "rcds008",
      name: "그린티 로션 포맨 150mL",
      hashTag: ["남성수분케어", "그린티"],
      frontImg: "rdIF_8.jpg",
      backImg: "rdIB_8.jpg",
    },
    {
      id: "rcds009",
      name: "파워프루프 브러시 라이너 0.6g",
      hashTag: ["총알픽싱라이너", "멀리프루프"],
      frontImg: "rdIF_9.jpg",
      backImg: "rdIB_9.jpg",
    },
    {
      id: "rcds010",
      name: "애플씨드 클렌징 오일 150mL",
      hashTag: ["클렌징오일판매1위", "사과추출물"],
      frontImg: "rdIF_10.jpg",
      backImg: "rdIB_10.jpg",
    },
    {
      id: "rcds011",
      name: "블랙티 유스 인핸싱 앰플 마스크 세트 28mL * 5ea",
      hashTag: ["주름개선미백기능성", "블랙티"],
      frontImg: "rdIF_11.jpg",
      backImg: "rdIB_11.jpg",
    },
    {
      id: "rcds012",
      name: "트루 마데카소사이드 레드 진정크림 기획세트 50mL+30mL(증정)",
      hashTag: ["저자극", "마데카소사이드"],
      frontImg: "rdIF_12.jpg",
      backImg: "rdIB_12.jpg",
    },
  ];
}
